package cm.aptoide.pt;


public enum EnumStoreTheme {
	
	APTOIDE_STORE_THEME_DEFAULT,
	APTOIDE_STORE_THEME_MIDNIGHT,
	APTOIDE_STORE_THEME_MAROON, 
	APTOIDE_STORE_THEME_GOLD,
	APTOIDE_STORE_THEME_ORANGE,
	APTOIDE_STORE_THEME_SPRINGGREEN, 
	APTOIDE_STORE_THEME_MAGENTA,
	APTOIDE_STORE_THEME_LIGHTSKY,
	APTOIDE_STORE_THEME_PINK, 
	APTOIDE_STORE_THEME_BLUE,
	APTOIDE_STORE_THEME_RED, 
	APTOIDE_STORE_THEME_SLATEGRAY, 
	APTOIDE_STORE_THEME_SEAGREEN, 
	APTOIDE_STORE_THEME_SILVER, 
	APTOIDE_STORE_THEME_DIMGRAY;
	
	public static EnumStoreTheme reverseOrdinal(int ordinal){
		return values()[ordinal];
	}
}
